name: Build

on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: ['3.8', '3.7', '3.6']
        architecture: ['x64', 'x86']
        include:
        - os: ubuntu-latest
          python: '3.x'
          architecture: 'x64'

    steps:
    - uses: actions/checkout@v2
    - if: github.event.ref_type != 'tag'
      run: |
        git fetch --prune --unshallow
        git tag -d $(git tag --points-at HEAD)
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}
    - run: python -m pip install --upgrade pip setuptools wheel setuptools_scm

    - run: python setup.py bdist_wheel

    - if: strategy.job-index == 0
      run: python setup.py sdist
    
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist

    - name: TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.testpypi }}
        repository_url: https://test.pypi.org/legacy/

    - name: PyPI
      if: github.event.ref_type == 'tag'
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.pypi }}