name: Build

on: [push]

jobs:
  build_wheels:
    name: Build impure wheels
    runs-on: windows-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8']
        architecture: ['x64', 'x86']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: |
        git fetch --prune --unshallow
        git describe --tags
        git log -1

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: Build wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python setup.py bdist_wheel

    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./dist