name: Build

on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'


jobs:
  build:
    name: Build wheels and sdist and upload to PyPI/TestPyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: ['3.6', '3.7', '3.8']
        architecture: ['x64', 'x86']
        include:
        - os: ubuntu-latest
          python: '3.x'
          architecture: 'x64'

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}
    - run: python -m pip install --upgrade pip setuptools wheel setuptools_scm

    - run: python setup.py bdist_wheel

    - if: matrix.os == 'ubuntu-latest'
      run: python setup.py sdist
    
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist


  upload:
    name: Upload to PyPI/TestPyPI
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/setup-python@v2
    - run: pip install --upgrade twine

    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist

    - name: Upload to TestPyPI
      run: |
        TWINE_USERNAME=__token__ \
        TWINE_PASSWORD="${{ secrets.testpypi }}" \
        TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/ \
        twine upload --skip-existing dist/*

    - name: Upload to PyPI
      if: github.event.ref_type == 'tag'
      run: |
        TWINE_USERNAME=__token__ \
        TWINE_PASSWORD="${{ secrets.pypi }}" \
        twine upload --skip-existing dist/*