name: Windows Test

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
      - name: Install example app
        run: |
          pip install -e example
          desktop-app install oink
          get-StartApps | findstr -I oink
