name: Windows Test

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
      - name: Install example app
        run: |
          pip install -e example
          desktop-app install oink
          get-StartApps | findstr -I oink
      - name: Install test dependencies
        run: pip install Pillow pyscreenshot
      - name: Run example app
        run: |
          invoke-item "$Env:APPDATA\Microsoft\Windows\Start Menu\Programs\Old McDonald's Farm\Oink App.lnk"
          python -c "from pyscreenshot import grab; im = grab(); im.save('screenshot.png')"
      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png